### ISSUE TITLE
Allow for a list of channels to be passed in

### ISSUE THREAD

**Issue by Skarlso** [actions-ecosystem/action-slack-notifier#334]
## What you want to add

```yaml
      - name: slack on failure
        if: failure()
        uses: actions-ecosystem/action-slack-notifier@fc778468d09c43a6f4d1b8cccaca59766656996a
        with:
          slack_token: <token>
          message: "${{ inputs.name }} has failed"
          channel: channel1, channel2, channel3
          color: red
          verbose: true
```

## Why this is needed

Because instead of duplicating the action three times, this is a much nicer approach. And it would be relatively easy to implement. Just check if channel contains `,` then do a loop and send it to all channels.
